### ISSUE TITLE
No results message on any search

### ISSUE THREAD

**Issue by ddimitrioglo** [AlexanderC/seasonvarcik#2]
![image](https://user-images.githubusercontent.com/9005667/32572690-0dcee85e-c4d4-11e7-944d-4ac5f5637f01.png)

P.S. MacOS 10.13.1

**Comment by thecotne** [comment]
try #1

**Comment by ddimitrioglo** [comment]
@thecotne could you please help me, how to build `seasonvarcik-vX.X.X-darwin-x64.dmg` with your fix?

**Comment by thecotne** [comment]
```bash
npm install
npm build
```

probably (i was testing it with `npm start`)

**Comment by ddimitrioglo** [comment]
@thecotne it didn't help...

**Comment by AlexanderC** [comment]
I’ll build guys)) sorjan zaguljal)

**Comment by ddimitrioglo** [comment]
@AlexanderC confirm that the issue was fixed 😉  thanks!
![image](https://user-images.githubusercontent.com/9005667/36252390-2d8c30a4-124d-11e8-9dd6-6b9c76640cca.png)
